### ISSUE TITLE
Fails when extracting files simultaneously

### ISSUE THREAD

**Issue by cory2067** [ZJONSSON/node-unzipper#103]
I have a zip of around 5 files. I try to extract them all as follows:
```
const mapdata = await Promise.all(mapfiles.map(file => file.buffer()));
```

However, this often (unpredictably) yields the following error:
```
(node:21288) UnhandledPromiseRejectionWarning: Error: FILE_ENDED
    at PullStream.pull (/home/cor/Desktop/webtaiko/node_modules/unzipper/lib/PullStream.js:78:28)
    at PullStream.emit (events.js:182:13)
    at PullStream.<anonymous> (/home/cor/Desktop/webtaiko/node_modules/unzipper/lib/PullStream.js:20:10)
    at PullStream.emit (events.js:182:13)
    at finishMaybe (_stream_writable.js:641:14)
    at afterWrite (_stream_writable.js:481:3)
    at onwrite (_stream_writable.js:471:7)
    at /home/cor/Desktop/webtaiko/node_modules/unzipper/lib/PullStream.js:70:11
    at afterWrite (_stream_writable.js:480:3)
    at process._tickCallback (internal/process/next_tick.js:63:19)
(node:21288) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:21288) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

But if I rewrite the code as follows, it seems to work without error
```
  let mapdata = [];
  for (const file of mapfiles) {
    // Note: deliberately doing these synchonously
    mapdata.push(await file.buffer());
  }
```

I'd like to clarify if this is a bug, or if this library does not support async like this.

**Comment by ZJONSSON** [comment]
This should work in general, see https://github.com/ZJONSSON/node-unzipper/pull/127 
The FILE_ENDED error is a generic error where the pullstream expected more data but didn't receive it.    What transport are you using (file, request, s3 etc?)

**Comment by ZJONSSON** [comment]
Please reopen if you are still facing this issue, with full details per above
