### ISSUE TITLE
Error: FILE_ENDED

### ISSUE THREAD

**Issue by kottkrig** [ZJONSSON/node-unzipper#156]
I'm getting the following error when trying to decompress this zip file: [14011284.zip](https://github.com/ZJONSSON/node-unzipper/files/3685121/14011284.zip). The OS itself can decompress the file just fine but it fails when decompressing through my nodejs application.

```javascript
fs.createReadStream(filePath)
      .pipe(unzipper.Extract({ path: destinationPath }))
      .on("error", reject)
      .on("finish", () => resolve(destinationPath))
```

Error:

```
Error: FILE_ENDED
    at Parse.pull (./node_modules/unzipper/lib/PullStream.js:83:28)
    at Parse.emit (events.js:200:13)
    at Parse.<anonymous> (./node_modules/unzipper/lib/PullStream.js:20:10)
    at Parse.emit (events.js:205:15)
    at finishMaybe (_stream_writable.js:644:14)
    at endWritable (_stream_writable.js:661:3)
    at Parse.Writable.end (_stream_writable.js:592:5)
    at DuplexWrapper.<anonymous> (./node_modules/duplexer2/index.js:29:14)
    at Object.onceWrapper (events.js:288:20)
    at DuplexWrapper.emit (events.js:205:15)
    at finishMaybe (./node_modules/readable-stream/lib/_stream_writable.js:630:14)
    at afterWrite (./node_modules/readable-stream/lib/_stream_writable.js:492:3)
    at onwrite (./node_modules/readable-stream/lib/_stream_writable.js:483:7)
    at WritableState.onwrite (./node_modules/readable-stream/lib/_stream_writable.js:180:5)
    at afterWrite (_stream_writable.js:483:3)
    at onwrite (_stream_writable.js:474:7)
```

**Comment by kottkrig** [comment]
Closing due to user error. My script didn't finish the download of the file completely before trying to extract the zip.
