### ISSUE TITLE
const { Math, Object } = primordials; ^  ReferenceError: primordials is not defined

### ISSUE THREAD

**Issue by Killa4** [ZJONSSON/node-unzipper#174]
Node Version - v12.14.1
NPM Version - 6.13.4

> ReferenceError: primordials is not defined
    at fs.js:27:26
    at req_ (C:\Users\killa\Documents\projects\rusticated\ClientRedo\node_modules\natives\index.js:143:24)
    at Object.req [as require] (C:\Users\killa\Documents\projects\rusticated\ClientRedo\node_modules\natives\index.js:55:10)
    at Object.<anonymous> (C:\Users\killa\Documents\projects\rusticated\ClientRedo\node_modules\unzip\node_modules\graceful-fs\fs.js:1:37)
    at Module._compile (internal/modules/cjs/loader.js:955:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:991:10)
    at Module.load (internal/modules/cjs/loader.js:811:32)
    at Function.Module._load (internal/modules/cjs/loader.js:723:14)
    at Module.require (internal/modules/cjs/loader.js:848:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (C:\Users\killa\Documents\projects\rusticated\ClientRedo\node_modules\unzip\node_modules\graceful-fs\graceful-fs.js:3:27)
    at Module._compile (internal/modules/cjs/loader.js:955:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:991:10)
    at Module.load (internal/modules/cjs/loader.js:811:32)
    at Function.Module._load (internal/modules/cjs/loader.js:723:14)
    at Module.require (internal/modules/cjs/loader.js:848:19)

**Comment by debelop13** [comment]
Same issue

**Comment by Killa4** [comment]
To fix it you need to revert back to node v10.16.0. The weird thing is it works on my local machine on the latest Node version but when I put it in production on my other machines it breaks with that error. So I reverted all to v10.16.0 for the time being.
