### ISSUE TITLE
"not found" error when used with AWS Lambda Environment

### ISSUE THREAD

**Issue by monkeybanana550** [ZJONSSON/node-unzipper#235]
I follow [this code within the documentation](https://www.npmjs.com/package/unzipper#opens3aws-sdk-params-options) wherein I need to use that code to use it for AWS:
```
const unzipper = require('./unzip');
const AWS = require('aws-sdk');
const s3Client = AWS.S3(config);
 
async function main() {
  const directory = await unzipper.Open.s3(s3Client,{Bucket: 'unzipper', Key: 'archive.zip'});
  return new Promise( (resolve, reject) => {
    directory.files[0]
      .stream()
      .pipe(fs.createWriteStream('firstFile'))
      .on('error',reject)
      .on('finish',resolve)
  });
}
 
main();
```
Now, I need to use it for the Lambda, and here's how I set up mine:
```
console.log('Loading function');

const aws = require('aws-sdk');

const s3Client = new aws.S3({ apiVersion: '2006-03-01' });

const unzipper = require("unzipper");

exports.handler = async (event) => {
    const bucket = 'this-bucket';
    const filename = JSON.stringify(event.Records[0].s3.object.key.replace(/\+/g, ' '), null, 2);
    const filepath = filename.substring(0, filename.lastIndexOf("/") + 1);
    
    console.log("Filename: " + filename);
    // Filename: "folder/folder/events.zip
    
    console.log("Filepath: " + filepath);
    // Filepath: "folder/folder/
    
    const directory = await unzipper.Open.s3(s3Client, { Bucket: bucket, Key: filename });
    return new Promise((resolve, reject) => {
        directory.files[0]
            .stream()
            .pipe(s3Client.createWriteStream(filepath))
            .on('error', reject)
            .on('finish', resolve)
    });
};
```
The only notable change I did would be the line in the `pipe(s3Client.createWriteStream(filepath))` wherein rather than using the `fs`, I used the `s3Client` because [this tutorial said so](https://multiaki.medium.com/unzipping-s3-files-back-to-s3-without-uncompressing-entire-file-streaming-82f662b5065a) at the step 2:

> In the code above I needed to replace “fs” to “s3”. It took me two days to come up with the code. I did not work with node streams before [https://nodejs.org/api/stream.html]. Even after writing a code, I was not sure whether the code is streamed or buffered in the memory before streaming. After talking to Ziggy Jonsson, the owner of the code, I could solve the issue. I truly appreciate his help.

Now, here's the error I'm receiving:
```
{
    "errorType": "NotFound",
    "errorMessage": null,
    "code": "NotFound",
    "message": null,
    "region": null,
    "time": "2021-04-15T06:57:23.638Z",
    "requestId": "WV6DR5HSH0C6TXDN",
    "extendedRequestId": "nEl1mjL5hgAnBpJG0F4Fqy8XdCzA1LRYxttu0nOsogPsspiWmR0vY3dmvDWZJHjc6axBFJ8q/F4=",
    "statusCode": 404,
    "retryable": false,
    "retryDelay": 20.66776038157996,
    "stack": [
        "NotFound: null",
        "    at Request.extractError (/opt/nodejs/node_modules/aws-sdk/lib/services/s3.js:698:35)",
        "    at Request.callListeners (/opt/nodejs/node_modules/aws-sdk/lib/sequential_executor.js:106:20)",
        "    at Request.emit (/opt/nodejs/node_modules/aws-sdk/lib/sequential_executor.js:78:10)",
        "    at Request.emit (/opt/nodejs/node_modules/aws-sdk/lib/request.js:688:14)",
        "    at Request.transition (/opt/nodejs/node_modules/aws-sdk/lib/request.js:22:10)",
        "    at AcceptorStateMachine.runTo (/opt/nodejs/node_modules/aws-sdk/lib/state_machine.js:14:12)",
        "    at /opt/nodejs/node_modules/aws-sdk/lib/state_machine.js:26:10",
        "    at Request.<anonymous> (/opt/nodejs/node_modules/aws-sdk/lib/request.js:38:9)",
        "    at Request.<anonymous> (/opt/nodejs/node_modules/aws-sdk/lib/request.js:690:12)",
        "    at Request.callListeners (/opt/nodejs/node_modules/aws-sdk/lib/sequential_executor.js:116:18)",
        "    at Request.emit (/opt/nodejs/node_modules/aws-sdk/lib/sequential_executor.js:78:10)",
        "    at Request.emit (/opt/nodejs/node_modules/aws-sdk/lib/request.js:688:14)",
        "    at Request.transition (/opt/nodejs/node_modules/aws-sdk/lib/request.js:22:10)",
        "    at AcceptorStateMachine.runTo (/opt/nodejs/node_modules/aws-sdk/lib/state_machine.js:14:12)",
        "    at /opt/nodejs/node_modules/aws-sdk/lib/state_machine.js:26:10",
        "    at Request.<anonymous> (/opt/nodejs/node_modules/aws-sdk/lib/request.js:38:9)"
    ]
}
```

It says "not found" but what exactly is the thing that it cannot find?

And yes I still can't unzip my file inside S3.

**Comment by monkeybanana550** [comment]
After some hours of checking what could be the problem, it might be about my permissions in IAM roles not set up properly. The Lambda functions should also be set up properly.

But after fixing those permissions, I encountered another problem. "NoSuchKeyExists", which I fixed by fixing the key using `decodeURIComponent()` and replacing each `+` with ` `:
```
const filename = decodeURIComponent(event.Records[0].s3.object.key.replace(/\+/g, ' '));
```.
Closing this now.
