### ISSUE TITLE
async iteration example no longer works in Node 18x, 19x

### ISSUE THREAD

**Issue by shivak** [ZJONSSON/node-unzipper#273]
The async iteration example from the middle of README.md now results in the following error:
```
Error [ERR_STREAM_PREMATURE_CLOSE]: Premature close
    at new NodeError (node:internal/errors:393:5)
    at Parse.onclose (node:internal/streams/end-of-stream:143:30)
    at Parse.emit (node:events:525:35)
    at Parse.<anonymous> (/***/node_modules/unzipper/lib/parse.js:29:10)
    at Parse.emit (node:events:525:35)
    at finish (node:internal/streams/writable:750:10)
    at finishMaybe (node:internal/streams/writable:735:9)
    at afterWrite (node:internal/streams/writable:507:3)
    at onwrite (node:internal/streams/writable:480:7)
    at cb (/***/node_modules/unzipper/lib/PullStream.js:43:14)
    at /***/node_modules/unzipper/lib/PullStream.js:76:91
    at afterWrite (node:internal/streams/writable:500:5)
    at afterWriteTick (node:internal/streams/writable:487:10)
    at process.processTicksAndRejections (node:internal/process/task_queues:81:21) {
  code: 'ERR_STREAM_PREMATURE_CLOSE'
}
```
Tested with multiple zip files on both Node 19.1.0 and 18.9.1

**Comment by igorrybak** [comment]
The same problem was discussed in #228. @wolfymaster's [solution](https://github.com/ZJONSSON/node-unzipper/issues/228#issuecomment-1294451911) works for me.

**Comment by Durisvk** [comment]
Even the tests are failing from as far as Node version 15:

```
node:events:346
      throw er; // Unhandled 'error' event
      ^

Error: aborted
    at connResetException (node:internal/errors:642:14)
    at TLSSocket.socketCloseListener (node:_http_client:424:27)
    at TLSSocket.emit (node:events:381:22)
    at node:net:666:12
    at TCP.done (node:_tls_wrap:577:7)
Emitted 'error' event on Request instance at:
    at Request.onerror (node:internal/streams/legacy:62:12)
    at Request.emit (node:events:369:20)
    at IncomingMessage.<anonymous> (/Users/Durisvk/opensource/node-unzipper/node_modules/request/request.js:1079:12)
    at IncomingMessage.emit (node:events:369:20)
    at TLSSocket.socketCloseListener (node:_http_client:424:13)
    at TLSSocket.emit (node:events:381:22)
    at node:net:666:12
    at TCP.done (node:_tls_wrap:577:7) {
  code: 'ECONNRESET'
}
not ok test/extractFromUrl.js ........................... 0/1
    Command: "/Users/Durisvk/.nvm/versions/node/v15.14.0/bin/node extractFromUrl.js"
    TAP version 13
    not ok 1 test/extractFromUrl.js
      ---
        exit:    1
        stderr:  |
          node:events:346
                throw er; // Unhandled 'error' event
                ^
          
          Error: aborted
              at connResetException (node:internal/errors:642:14)
              at TLSSocket.socketCloseListener (node:_http_client:424:27)
              at TLSSocket.emit (node:events:381:22)
              at node:net:666:12
              at TCP.done (node:_tls_wrap:577:7)
          Emitted 'error' event on Request instance at:
              at Request.onerror (node:internal/streams/legacy:62:12)
              at Request.emit (node:events:369:20)
              at IncomingMessage.<anonymous> (/Users/Durisvk/opensource/node-unzipper/node_modules/request/request.js:1079:12)
              at IncomingMessage.emit (node:events:369:20)
              at TLSSocket.socketCloseListener (node:_http_client:424:13)
              at TLSSocket.emit (node:events:381:22)
              at node:net:666:12
              at TCP.done (node:_tls_wrap:577:7) {
            code: 'ECONNRESET'
          }
        command: "/Users/Durisvk/.nvm/versions/node/v15.14.0/bin/node extractFromUrl.js"
      ...
    
    1..1
    # tests 1
    # fail  1
```

The tests start working again when switching to Node v14.

I recommend extending [travis.yml](https://github.com/ZJONSSON/node-unzipper/blob/master/.travis.yml) with new versions  and maybe even adding `lts/*` as a version to catch these kinds of issues sooner.

**Comment by ZJONSSON** [comment]
This PR has been published as a patch https://github.com/ZJONSSON/node-unzipper/pull/274
