### ISSUE TITLE
How to use Open.url with native "fetch"?

### ISSUE THREAD

**Issue by lucasrmendonca** [ZJONSSON/node-unzipper#292]
How do I use Open.url with native "fetch" on Node.js v20.9.0 ?

```js
const directory = await unzipper.Open.url(fetch, 'https://www.dwsamplefiles.com/?dl_id=559');
```
```
TypeError: Failed to parse URL from [object Object]
    at Object.fetch (node:internal/deps/undici/undici:11372:11) {
  [cause]: TypeError: Invalid URL
      at new URL (node:internal/url:775:36)
      at new _Request (node:internal/deps/undici/undici:5055:25)
      at fetch2 (node:internal/deps/undici/undici:9195:25)
      at Object.fetch (node:internal/deps/undici/undici:11370:18)
      at fetch (node:internal/process/pre_execution:282:25)
      at /home/<user>/<project>/node_modules/unzipper/lib/Open/index.js:59:21
      at Promise._execute (/home/<user>/<project>/node_modules/bluebird/js/release/debuggability.js:300:9)
      at Promise._resolveFromExecutor (/home/<user>/<project>/node_modules/bluebird/js/release/promise.js:481:18)
      at new Promise (/home/<user>/<project>/node_modules/bluebird/js/release/promise.js:77:14)
      at Object.size (/home/<user>/<project>/node_modules/unzipper/lib/Open/index.js:58:16)
      at centralDirectory (/home/<user>/<project>/node_modules/unzipper/lib/Open/directory.js:93:17)
      at Object.url (/home/<user>/<project>/node_modules/unzipper/lib/Open/index.js:71:12)
      at start (file:///home/<user>/<project>/index.js:120:45) {
    code: 'ERR_INVALID_URL',
    input: '[object Object]'
  }
}
```

**Comment by sethtjf** [comment]
did you ever get this working?

**Comment by lucasrmendonca** [comment]
Nope, I went with `Open.file` instead of `Open.url` since the latter seems to only work with the "requests" library and I didn't want to download another dependency just for that

**Comment by ZJONSSON** [comment]
It would make sense to move to fetch (ideally with backward compatibility for request)

**Comment by rdsedmundo** [comment]
I was also looking for that because `request` is now deprecated and also has an open CVE.

**Comment by ZJONSSON** [comment]
Open to PRs, if not I will find time to do this at some point, hopefully soon!

**Comment by jpambrun** [comment]
I just stumbled on this issue.

It's not a complete solution, but I have a start of an implementation with fetch in this issue https://github.com/ZJONSSON/node-unzipper/issues/309#issue-2267169008. I needs better error handling which I am struggling with.

**Comment by sethtjf** [comment]
I was able to hack something together using got but found it unreliable for my use case bc of the location of the central directory at the end of the zip file.

**Comment by ecofi** [comment]
May I ask whether the .url method would have any benefits compared to .buffer()? 

Am I write that the received directory variable would be of same size regardless whether .url() or .buffer() is used? 
In this case, the only benefit for .url() would be to save memory in avoiding the zip file fully loaded to a buffer first?

**Comment by willem-syt** [comment]
I got fetch working like this. It is only used in one case, so it has not been tested thoroughly :)
```
import fetch from 'node-fetch';
import unzipper from 'unzipper';

async getZipFile() {
        try {
            const response = await fetch('https://some-zip-file.zip', { method: 'GET' });
            if (response.ok && response.status === 200) {
                const arrayBuffer = await response.arrayBuffer();
                const zipDirectory = await unzipper.Open.buffer(Buffer.from(arrayBuffer));
                const dataFile = zipDirectory.files.find(d => d.path === 'myfile.txt');
                return dataFile;
            }
            else {
                // error
            }
        }
        catch (err) {
            // error.
        }
    }
```

Then use the `dataFile.stream()` to access it.
