### ISSUE TITLE
Open.file Promise does not catch all errors

### ISSUE THREAD

**Issue by fiws** [ZJONSSON/node-unzipper#91]
I would expect that `Open.file` "rejects" all errors, promise style. But it does not:

example.js:
```js
const unzipper = require('unzipper');

unzipper.Open.file('./example.js')
  .then(console.log)
  .catch(console.error)
  .then(() => console.log('this log should appear, but does not'));
```
Reading a js file should fail, but not crash the node process. The above example results in:

```
events.js:174
      throw er; // Unhandled 'error' event
      ^

Error: FILE_ENDED
    at PullStream.pull (/project/node_modules/unzipper/lib/PullStream.js:72:28)
    at PullStream.emit (events.js:189:13)
    at PullStream.<anonymous> (/project/node_modules/unzipper/lib/PullStream.js:20:10)
    at PullStream.emit (events.js:194:15)
    at finishMaybe (_stream_writable.js:646:14)
    at endWritable (_stream_writable.js:663:3)
    at PullStream.Writable.end (_stream_writable.js:594:5)
    at ReadStream.onend (_stream_readable.js:633:10)
    at Object.onceWrapper (events.js:277:13)
    at ReadStream.emit (events.js:194:15)
    at endReadableNT (_stream_readable.js:1107:12)
    at process.internalTickCallback (internal/process/next_tick.js:72:19)
Emitted 'error' event at:
    at errorOrDestroy (internal/streams/destroy.js:98:12)
    at PullStream.onerror (_stream_readable.js:695:7)
    at PullStream.emit (events.js:189:13)
    at PullStream.pull (/project/node_modules/unzipper/lib/PullStream.js:72:14)
    at PullStream.emit (events.js:189:13)
    [... lines matching original stack trace ...]
    at process.internalTickCallback (internal/process/next_tick.js:72:19)
```

**Comment by ZJONSSON** [comment]
Good catch @fiws - please submit a PR if you have a fix in mind - otherwise I'll take a look
